### ISSUE TITLE
v4.0.0 Release

### ISSUE THREAD

**Issue by niftylettuce** [forwardemail/free-email-forwarding#189]
- [ ] Install and document installation for Pyzor SpamAssassin plugin https://spamassassin.apache.org/full/3.3.x/doc/Mail_SpamAssassin_Plugin_Pyzor.html (ref: https://forums.zimbra.org/viewtopic.php?t=65628#p288618)
- [ ] Install and document installation for Razor2 SpamAssassin plugin https://spamassassin.apache.org/full/3.2.x/doc/Mail_SpamAssassin_Plugin_Razor2.html (ref: https://forums.zimbra.org/viewtopic.php?t=65628#p288618)

**Comment by niftylettuce** [comment]
- [ ] SRS "To" header needs test and auto-rewrite since some mail implementations out there don't abide by SRS only being relevant to Mail From on envelope
- [ ] Document subdomain setup in FAQ #221 #15 
- [ ] Limit aliases to (10) recipients in dashboard (since that is new system-wide default)
- [ ] Increase word count on help form to 2000+ characters
- [ ] Captcha for signup + help (until verified, a captcha is always required)
- [ ] 30 day free trial
- [ ] Pass Hardenize, SSL Labs, Mozilla Observatory tests and then submit again to PRISM + PrivacyTools.io lists (along with screenshots and links to passing tests)
- [ ] Slack alerts on rate limiting abuse
- [ ] Fix dmarc-parse bug <https://github.com/softvu/dmarc-parse/issues/2>
- [ ] ARF report parsing for abuse@ and postmaster@ emails, using child spawned <https://github.com/danielsen/arf> - which is then fed through to SpamService for manual control whether it is marked as spam or ham
- [ ] API + Browser Extension (e.g. crud alias stuff #208 
- [ ] HSTS preloaded for *.forwardemail.net
- [ ] Automatic email notifications for DNS changes and validation failed vs. passed every X hours
- [ ] Hint to user if they made a typo and both MX records are mx1 and mx1 vs mx1 and mx2 (common issue)
- [ ] Enable OTP/TFA #213 per https://github.com/forwardemail/forwardemail.net/pull/18 and https://github.com/forwardemail/forwardemail.net/pull/21
- [ ] Setup unbound + netplan on servers with Cloudflare + caching per #223 
- [ ] Document in FAQ that alias recipients individually receive a copy, they are not all sent to the recipients in the "To" field as one bulk email #211 
- [ ] Document suggestion for Gmail authentication failure #185 
- [ ] Document rate limiting (e.g. 200 -> 300) and limited per unique sender email address #179 with an expiry of X seconds
- [ ] Ability to forward to a port different than 25 per #163 
- [ ] Implement SpamScanner, Malwareworld.com/OpenPhish/PhishTnak/URLHaus #17 #114 
- [ ] Pass through MX if no recipients found (interesting feature idea) #44

**Comment by niftylettuce** [comment]
Ability to forward to a port different than 25 now resolved, see #163

**Comment by niftylettuce** [comment]
- [ ] when I release ansible config, need to make sure this is in it https://github.com/geerlingguy/ansible-role-clamav
